#!/bin/sh

# set -eux

# WSL
remote_ip=$(
  ip addr |
  awk '/inet / && !/127.0.0.1/ { split($2,a,"/"); print a[1] }'
)

prefix=/mnt/c/'Program Files'/VcXsrv

# export DISPLAY=127.0.0.1:0.0
WSLENV=DISPLAY "${prefix}"/xhost.exe +inet:${remote_ip}
WSLENV=DISPLAY "${prefix}"/xhost.exe -
