#!/bin/sh

# set -eux

cmd="Test-Connection -ComputerName (hostname) -Count 1"

output=$(/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe \
  -Command "(${cmd}).IPV4Address.IPAddressToString")

echo "${output}" | sed -u 's/\r//'
