#!/bin/sh

# set -eux

dir=$(dirname $(realpath -e $0))

listen_address="0.0.0.0"
port=2222

address=$(sh $dir/print-ipaddress)

# WSL
remote_ip=$(
  ip addr |
  awk '/inet / && !/127.0.0.1/ { split($2,a,"/"); print a[1] }'
)

prefix=/mnt/c/Windows/System32

function run_as_netsh() {
  local cmd=$1

  $prefix/WindowsPowerShell/v1.0/powershell.exe \
    -Command "Start-Process netsh.exe -ArgumentList \"${cmd}\" -Verb RunAs"
}

# TODO: Set firewall rule as the same as the one for X11 at here

reset_cmd="interface portproxy reset"
run_as_netsh "${reset_cmd}"

# for SSH
set_cmd="interface portproxy add v4tov4 listenaddress=${listen_address} \
listenport=${port} connectaddress=${remote_ip} connectport=${port}"
run_as_netsh "${set_cmd}"

echo "ssh:"
echo "  address: \"${address}\""
echo "  port: \"${port}\""
